baseURL = 'https://www.tormakristof.eu/'
languageCode = 'en-us'
title = 'Kristóf Torma'
paginate = 5
[[module.imports]]
path = 'github.com/CaiJimmy/hugo-theme-stack/v3'
disable = false

[params]

  [params.sidebar]
  subtitle = 'DevOps Enginner'

    [params.sidebar.avatar]
    enabled = true
    local = true
    src = 'avatar.jpg'

  [params.article]
  math = false
  toc = true
  readingTime = true
