baseURL = 'https://www.tormakristof.eu/'
languageCode = 'en-us'
title = 'Kristóf Torma'
paginate = 5
[[module.imports]]
path = 'github.com/CaiJimmy/hugo-theme-stack/v3'
disable = false

[params]

  [params.sidebar]
  subtitle = 'DevOps Enginner'

    [params.sidebar.avatar]
    enabled = true
    local = true
    src = 'avatar.jpg'

  [params.article]
  math = false
  toc = true
  readingTime = true
[[menu.main]]
identifier = "linkedin"
name = "LinkedIn"
url = "https://www.linkedin.com/in/tormakris"

  [menu.main.params]
  icon = "brand-linkedin"

[[menu.main]]
identifier = "github"
name = "GitHub"
url = "https://github.com/tormachris"

  [menu.main.params]
  icon = "brand-github"


[[menu.main]]
identifier = "cv"
name = "CV"
url = "https://cv.tormakristof.eu"

  [menu.main.params]
  icon = "file-certificate"
