baseURL = 'https://www.tormakristof.eu/'
languageCode = 'en-us'
title = 'HomeLab misadventures'
paginate = 5
theme = "anubis"
enableRobotsTXT: true


[params]
author = "Kristof Torma"
email = "iam@tormakristof.eu"
copyCodeButton: true

  [params.sidebar]
  subtitle = 'DevOps Enginner'

    [params.sidebar.avatar]
    enabled = true
    local = true
    src = 'avatar.jpg'

  [params.article]
  math = false
  toc = true
  readingTime = true

[[menu.main]]
identifier = "cv"
name = "CV"
url = "https://cv.tormakristof.eu"

  [menu.main.params]
  icon = "file-certificate"

[[menu.main]]
identifier = "github"
name = "GitHub"
url = "https://github.com/tormachris"

  [menu.main.params]
  icon = "brand-github"

[[menu.main]]
identifier = "linkedin"
name = "LinkedIn"
url = "https://www.linkedin.com/in/tormakris"

  [menu.main.params]
  icon = "brand-linkedin"
